#docker-compose up

php:
    build: .
    ports:
     - "9090:80"
     - "443:443"
    volumes:
     - ./public:/var/www/html
    links:
        - db
db:
    image: mysql:8
    ports:
        - "52000:3306"
    volumes:
        - /var/lib/mysql
    environment:
        - MYSQL_DATABASE=db_app_db2
        - MYSQL_ROOT_PASSWORD=123456

#docker exec -it app_bd2_db_1  mysql --user=root --password=123456
#select host, user from mysql.user;